name: LateX CV to PDF

on:
  push:
    branches: 
      - master
      - develop
    tags:
       - '*'
  pull_request:
    branches: [ master ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile test LaTeX document with Maths
        id: compile-latex-document-with-maths
        uses: ./
        with:
          output_dir: output
          main_latex_file: test.tex
          ctan_packages: amssymb latexsym amsmath
      - name: Upload PDF to the workflow tab
        id: upload-workflow-tab-maths
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output/test.pdf
      
      - name: Compile LaTeX document with fontawesome
        id: compile-latex-document-with-fontawesome
        uses: ./
        with:
          output_dir: output
          main_latex_file: test-fontawesome.tex
          ctan_packages: moderncv colortbl fontawesome
      - name: Upload PDF to the workflow tab
        id: upload-workflow-tab-fontawersome
        uses: actions/upload-artifact@v2
        with:
          name: output-fontawesome
          path: output/test-fontawesome.pdf
